### ISSUE TITLE
history中的url似乎不可访问

### ISSUE THREAD

**Issue by Taoshuaifei** [lyscf/gaokao-analytics#1]
history中提供的接口目前似乎不可访问，如https://[static-data.gaokao.cn/www/2.0/schoolspecialscore/20/2022/62.json](https://static-data.gaokao.cn/www/2.0/schoolspecialscore/20/2022/62.json)

**Comment by lyscf** [comment]
如果出现不可访问请尝试批量测试一下，因为部分学校对部分地区没有招生计划，这会导致返回空数据，我确定接口不存在问题，如https://static-data.gaokao.cn/www/2.0/schoolspecialscore/30/2022/62.json 如果您还存在问题，请再次回复我。
